clusterGroup:
  name: prod

  namespaces:
    vault:
    golang-external-secrets:
    redhat-ods-operator:
        operatorGroup: true
        targetNamespaces: []

  sharedValueFiles:
    - /overrides/values-{{ $.Values.global.device }}.yaml
    - /overrides/values-{{ $.Values.global.device }}-{{ $.Values.global.clusterPlatform }}.yaml

  subscriptions:
    rhoai:
      name: rhods-operator
      namespace: redhat-ods-operator
      channel: stable-3.x

  applications:
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      chart: golang-external-secrets
      chartVersion: 0.2.*

    vault:
      name: vault
      namespace: vault
      chart: hashicorp-vault
      chartVersion: 0.1.*

    rag-quickstart:
      name: rag-quickstart
      namespace: ai-quickstart-rag-prod
      repoURL: https://github.com/rh-ai-quickstart/RAG
      chartVersion: main
      path: deploy/helm/rag
      extraValueFiles:
        - /overrides/rag-quickstart.yaml
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: minio
          jsonPointers:
            - /data
        - group: datasciencepipelinesapplications.opendatahub.io
          kind: DataSciencePipelinesApplication
          jsonPointers:
            - /spec
        - group: kubeflow.org
          kind: Notebook
          jsonPointers:
            - /spec
            - /metadata/annotations
            - /metadata/labels
        - group: route.openshift.io
          kind: Route
          jsonPointers:
            - /spec/host
            - /spec/alternateBackends

    pattern-secrets:
      name: pattern-secrets
      namespace: ai-quickstart-rag-prod
      path: charts/pattern-secrets

    data-science-cluster:
      name: data-science-cluster
      namespace: ai-quickstart-rag-prod
      path: charts/dsc
